// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	AddAmountToBalance(ctx context.Context, arg AddAmountToBalanceParams) (Accounts, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Accounts, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entries, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfers, error)
	DeleteAccount(ctx context.Context, id int64) error
	GetAccountByID(ctx context.Context, id int64) (Accounts, error)
	GetAccountByIDForUpdate(ctx context.Context, id int64) (Accounts, error)
	GetAllAccounts(ctx context.Context, arg GetAllAccountsParams) ([]Accounts, error)
	GetEntry(ctx context.Context, id int64) (Entries, error)
	GetTransfer(ctx context.Context, id int64) (Transfers, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entries, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfers, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Accounts, error)
}

var _ Querier = (*Queries)(nil)
